title: Anna
description: "Your babysitter in Zug, ğŸ§‘â€ğŸ¼"
logo: /assets/images/photo.png
google_analytics: G-SNQQ1SBB6S
_root: unotutto.github.io

github:
  is_user_page: false

# theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
