title: Anna
description: "Your babysitter in Zug, ğŸ§‘â€ğŸ¼"
email: anna.babysitting.zug@gmail.com
logo: /assets/images/photo.png
google_analytics: G-SNQQ1SBB6S

theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
